image: meteorhacks/meteord

dashboard:
  image: unreal0/intermediate
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - MONGO_URL=mongodb://mongo/intermediate
   #- MONGO_URL = mongodb://u7DZw3XibjLz94JG:p4OmQKFSBxsy2NuU8@10.10.72.139:27017/JOQGwA8XdrNuzmKU
   #- ROOT_URL = http://unreal-cooks.daoapp.io

mongo:
  image: mongo:latest
